### ISSUE TITLE
Highlighting for tagged roles

### ISSUE THREAD

**Issue by RickDavis404** [haad/language-Ansible#10]
Can you add syntax highlighting when roles are tagged in playbooks...

example...

```

---
- name: My Play
  hosts: all 
  become: yes
  roles:
    - { role: common, tags: [ "common", "my_common_tag" ] }
```

The adding the config below works, but for some reason when I combine them together it malfunctions on the quoted strings for tags, so I'm probably getting lost in regex somewhere...

``` cson
# packages/language-ansible/grammars/ansible.cson
# works
  {
    captures:
      "2":
        name: "string.quoted.double.ansible"
    match: "\\- (\\{ role\\:) (\\w*)"
    name: "keyword.other.ansible"
  }
  {
    captures:
      "2":
        name: "string.quoted.double.ansible"
    match: "( tags\\:) \\[ ([[\\\"\\w*\\\"]+[,]? ]+) \\] \\}"
    name: "keyword.other.ansible"
  }

```

``` cson
# packages/language-ansible/grammars/ansible.cson
# doesn't work
  {
    captures:
      "2":
        name: "string.quoted.double.ansible"
    match: "\\- (\\{ role\\:) (\\w*)|( tags\\:) \\[ ([[\\\"\\w*\\\"]+[,]? ]+) \\] \\}"
    name: "keyword.other.ansible"
  }
```
