### ISSUE TITLE
Highlighting not perfect in variable list

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [haad/language-Ansible#17]
Hi,

First of all, **thank you** for your great Atom **language-Ansible** extension!

## The issue (short)

A bad highlighting is present in my global variable file

## Snippet

Here is the snippet of the global vars :
```
##############################
### Reverse Proxy / Nginx  ###
##############################
name_main_certificate: "{{ certbot_certs_list[0]['domains'][0] }}"
nginx_lb_le_domains:
      - name: "{{ certbot_certs_list[0]['domains'][0] }}"
        is_default: true
        with_ssl: true
        without_ssl: false
        request_acme_cert: false
      - name: "{{ certbot_certs_list[0]['domains'][1] }}"
        is_default: true
        with_ssl: true
        without_ssl: false
        request_acme_cert: false
      - name: "{{ certbot_certs_list[0]['domains'][2] }}"
        is_default: true
        with_ssl: true
        without_ssl: false
        request_acme_cert: false
```

## Explanation

So, the `"{{ certbot_certs_list[0]['domains'][0] }}"` have the right text highlighting, but for the 'name' inside the variable `nginx_lb_le_domains > name`, i don't think it's the right highlighting here, should be light brown, not green in my point of view, because it's a palceholder, not a normal 'name' value.

Thank you in advance for your reading ! :)
