### ISSUE TITLE
FQCNs are not highlighted

### ISSUE THREAD

**Issue by anjo-swe** [haad/language-Ansible#21]
```
- name: "install package"
  package:
    name: "package"

- name: "install package"
  ansible.builtin.package:
    name: "package"
```

![image](https://user-images.githubusercontent.com/1271892/145942142-338530bd-80de-494a-a997-b0d21a5dec50.png)

Tested using Atom 1.58 & language-ansible 0.2.2

Related to https://github.com/clifford-github/sublime-ansible/issues/27
